In [73]:
import numpy as np
import pandas as pd
import sklearn
import nltk
from nltk.stem.porter import PorterStemmer
from sklearn.metrics.pairwise import cosine_similarity


mv=pd.read_csv('xyz.csv')
print(mv.head())
#importing csv

  article                                              title  \
0       0                                           Preamble   
1       1                    Name and territory of the Union   
2       2           Admission or establishment of new States   
3       3  Formation of new States and alteration of area...   
4       4  Laws made under articles 2 and 3 to provide fo...   

                                         description  \
0  WE, THE PEOPLE OF INDIA, having solemnly resol...   
1  (1) India, that is Bharat, shall be a Union of...   
2  Parliament may by law admit into the Union, or...   
3  Parliament may by law—\n\n(a) form a new State...   
4   (1) Any law referred to in article 2 or artic...   

                                                tags  
0                                       ['preamble']  
1  ['name', 'and', 'the', 'union', 'territory', '...  
2  ['states', 'admission', 'establishment', 'new'...  
3  ['states', 'existing', 'boundaries', 'and', 'f...  
4  

In [74]:
mv.head()

article                                              title  \
0       0                                           Preamble   
1       1                    Name and territory of the Union   
2       2           Admission or establishment of new States   
3       3  Formation of new States and alteration of area...   
4       4  Laws made under articles 2 and 3 to provide fo...   

                                         description  \
0  WE, THE PEOPLE OF INDIA, having solemnly resol...   
1  (1) India, that is Bharat, shall be a Union of...   
2  Parliament may by law admit into the Union, or...   
3  Parliament may by law—\n\n(a) form a new State...   
4   (1) Any law referred to in article 2 or artic...   

                                                tags  
0                                       ['preamble']  
1  ['name', 'and', 'the', 'union', 'territory', '...  
2  ['states', 'admission', 'establishment', 'new'...  
3  ['states', 'existing', 'boundaries', 'and', 'f...  
4  ['laws', 'schedules', 'supplemental,', 'first'...

In [75]:
title=str(input())
for article, description in zip(mv['article'], mv['description']):
    if article == title:
        print(description)
        break
else:
    print('error')

preample
error


In [90]:
def convert2(obj):
    L=list(obj.split(' '))
    ll=[]
    for i in L:
        ll.append(i.lower())
    print(ll)
    return(list(set(ll)))
#function to raplace braces and make tags alphanumric only
def convert3(obj):
    s=""
    for i in obj:
        if i!=" ":
            s+=i
    return(s)
def convert4(obj):
    L=[obj]
    return(L)

In [91]:
mv['tags']=mv['title'].apply(convert2)
mv['article']=mv['article'].apply(convert3)
mv['tags']+=mv['article'].apply(convert4)

['preamble']
['name', 'and', 'territory', 'of', 'the', 'union']
['admission', 'or', 'establishment', 'of', 'new', 'states']
['formation', 'of', 'new', 'states', 'and', 'alteration', 'of', 'areas,', 'boundaries', 'or', 'names', 'of', 'existing', 'states']
['laws', 'made', 'under', 'articles', '2', 'and', '3', 'to', 'provide', 'for', 'the', 'amendment', 'of', 'the', 'first', 'and', 'the', 'fourth', 'schedules', 'and', 'supplemental,', 'incidental', 'and', 'consequential', 'matters']
['citizenship', 'at', 'the', 'commencement', 'of', 'the', 'constitution']
['rights', 'of', 'citizenship', 'of', 'certain', 'persons', 'who', 'have', 'migrated', 'to', 'india', 'from', 'pakistan']
['rights', 'of', 'citizenship', 'of', 'certain', 'migrants', 'to', 'pakistan']
['rights', 'of', 'citizenship', 'of', 'certain', 'persons', 'of', 'indian', 'origin', 'residing', 'outside', 'india']
['persons', 'voluntarily', 'acquiring', 'citizenship', 'of', 'a', 'foreign', 'state', 'not', 'to', 'be', 'citizens']
['co

In [92]:
mv.head()

article                                              title  \
0       0                                           Preamble   
1       1                    Name and territory of the Union   
2       2           Admission or establishment of new States   
3       3  Formation of new States and alteration of area...   
4       4  Laws made under articles 2 and 3 to provide fo...   

                                         description  \
0  WE, THE PEOPLE OF INDIA, having solemnly resol...   
1  (1) India, that is Bharat, shall be a Union of...   
2  Parliament may by law admit into the Union, or...   
3  Parliament may by law—\n\n(a) form a new State...   
4   (1) Any law referred to in article 2 or artic...   

                                                tags  
0                                      [preamble, 0]  
1          [name, and, the, union, territory, of, 1]  
2  [states, admission, establishment, new, or, of...  
3  [states, existing, boundaries, and, formation,...  
4  [laws, schedules, supplemental,, first, conseq...

In [93]:
mv.to_csv('xyz.csv', index=False)

In [ ]:
mv.iloc[4]['tags']

In [ ]:
mv['tags']=mv['tags'].apply(lambda x:" ".join(x))
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=500,stop_words='english')
vector = cv.fit_transform(mv['tags']).toarray().astype(float)
print(vector)
#creating the vector

In [51]:
cv.get_feature_names_out()

array(['188', 'abolition', 'account', 'accounts', 'acquisition', 'act',
       'acting', 'acts', 'additional', 'address', 'administration',
       'advise', 'advocate', 'affirmation', 'agreements', 'aid',
       'allowances', 'andhra', 'anglo', 'annual', 'appeal', 'appeals',
       'appellate', 'application', 'apply', 'appointment', 'appropriated',
       'appropriation', 'areas', 'article', 'articles', 'assam',
       'assemblies', 'assembly', 'assent', 'assets', 'attendance',
       'attorney', 'audit', 'auditor', 'authorities', 'authority', 'bar',
       'bills', 'board', 'borrowing', 'business', 'carry', 'carrying',
       'case', 'cases', 'caste', 'castes', 'casual', 'cease', 'ceasing',
       'census', 'central', 'certain', 'certificate', 'chairman',
       'chapter', 'chief', 'children', 'citizens', 'citizenship', 'civil',
       'claim', 'claims', 'class', 'classes', 'code', 'collected',
       'collection', 'commencement', 'commerce', 'commission',
       'commissions', 'commi

In [99]:
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import CountVectorizer

mv['tags'] = mv['tags'].apply(lambda x: " ".join(map(str, x)))

s = str(input())
s=s.upper().strip()
user_input=s.lower().strip()

user_vector = cv.transform([user_input]).toarray()

cosine_similarities = cosine_similarity(user_vector, vector)

top_indices = cosine_similarities.argsort()[0][-5:][::-1]

for index in top_indices:
    num=mv['article'][index]
    title = mv['title'][index]
    description = mv['description'][index]
    print(f"ArNumber {num}, Title: {title}, Description: {description}")


239A
ArNumber 395, Title: Repeals, Description: The Indian Independence Act, 1947, and the Government of India Act, 1935, together with all enactments amending or supplementing the latter Act, but not including the Abolition of Privy Council Jurisdiction Act, 1949, are hereby repealed.

ArNumber 146, Title: Officers and servants and the expenses of the Supreme Court, Description: (1) Appointments of officers and servants of the Supreme Court shall be made by the Chief Justice of India or such other Judge or officer of the Court as he may direct:

 

      Provided that the President may by rule require that in such cases as may be specified in the rule, no person not already attached to the Court shall be appointed to any office connected with the Court, save after consultation with the Union Public Service Commission.

 

(2) Subject to the provisions of any law made by Parliament, the conditions of service of officers and servants of the Supreme Court shall be such as may be prescrib

In [97]:
import numpy as np
import pandas as pd
import sklearn
import nltk
from nltk.stem.porter import PorterStemmer
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import CountVectorizer


def check(s):
    mv['tags'] = mv['tags'].apply(lambda x: " ".join(map(str, x)))

    user_input=s.lower().strip()

    user_vector = cv.transform([user_input]).toarray()

    cosine_similarities = cosine_similarity(user_vector, vector)

    top_indices = cosine_similarities.argsort()[0][-5:][::-1]

    for index in top_indices:
        num=mv['article'][index]
        title = mv['title'][index]
        description = mv['description'][index]
        print(f"ArNumber {num}, Title: {title}, Description: {description}")


mv=pd.read_csv('xyz.csv')
title=str(input())
for article, description in zip(mv['article'], mv['description']):
    if article == title:
        print(f"ArNumber {article}, Title: {title}, Description: {description}")
        break
else:
    check(title)

239a
ArNumber 395, Title: Repeals, Description: The Indian Independence Act, 1947, and the Government of India Act, 1935, together with all enactments amending or supplementing the latter Act, but not including the Abolition of Privy Council Jurisdiction Act, 1949, are hereby repealed.

ArNumber 146, Title: Officers and servants and the expenses of the Supreme Court, Description: (1) Appointments of officers and servants of the Supreme Court shall be made by the Chief Justice of India or such other Judge or officer of the Court as he may direct:

 

      Provided that the President may by rule require that in such cases as may be specified in the rule, no person not already attached to the Court shall be appointed to any office connected with the Court, save after consultation with the Union Public Service Commission.

 

(2) Subject to the provisions of any law made by Parliament, the conditions of service of officers and servants of the Supreme Court shall be such as may be prescrib

In [1]:
import numpy as np
import pandas as pd
import sklearn
import nltk
from nltk.stem.porter import PorterStemmer
from sklearn.metrics.pairwise import cosine_similarity


mv=pd.read_csv('que.csv')
print(mv.head())

                                              prompt  \
0  What is the definition of 'Panchayat' in the C...   
1  What is the Gram Sabha according to the Indian...   
2  What are the levels at which Panchayats are co...   
3  Can a state with a population not exceeding tw...   
4  What provisions can be made by the state legis...   

                                              output  
0  In the Constitution of India, a 'Panchayat' is...  
1  According to the Indian Constitution, the Gram...  
2  In India, Panchayats are constituted at the vi...  
3  No, states with a population not exceeding twe...  
4  The state legislature can make provisions conc...  


In [6]:
def changee(obj):
    L=list(obj.split(' '))
    ll=[]
    for i in L:
        ll.append(i.lower())
    lll=[]
    for j in ll:
        s=""
        for k in j:
            if k.isalnum():
                s+=k
        lll.append(s)
    #print(ll)
    return(list(set(lll)))
mv['tags']=mv['prompt'].apply(changee)

In [7]:
mv

prompt  \
0    What is the definition of 'Panchayat' in the C...   
1    What is the Gram Sabha according to the Indian...   
2    What are the levels at which Panchayats are co...   
3    Can a state with a population not exceeding tw...   
4    What provisions can be made by the state legis...   
..                                                 ...   
928  What are the provisions for salaries, allowanc...   
929  What is the procedure for transferring a Judge...   
930  What is the process for Judges of High Courts ...   
931  What are the powers of a High Court in relatio...   
932  What is the role of a High Court in a State ac...   

                                                output  \
0    In the Constitution of India, a 'Panchayat' is...   
1    According to the Indian Constitution, the Gram...   
2    In India, Panchayats are constituted at the vi...   
3    No, states with a population not exceeding twe...   
4    The state legislature can make provisions conc...   
..                                                 ...   
928  As per Article 221, Judges of each High Court ...   
929  As per Article 222, the President may, on the ...   
930  As per Article 219, every person appointed to ...   
931  As per Article 218, the provisions of clauses ...   
932  Article 214 of the Indian Constitution states ...   

                                                  tags  
0    [what, the, definition, panchayat, constitutio...  
1    [what, gram, the, to, sabha, constitution, is,...  
2    [levels, panchayats, what, the, constituted, w...  
3    [with, panchayats, the, twenty, a, level, stat...  
4    [panchayats, what, made, the, provisions, legi...  
..                                                 ...  
928  [what, judges, the, pension, provisions, high,...  
929  [what, high, the, judge, a, 222, one, court, p...  
930  [what, judges, the, high, 219, oath, or, affir...  
931  [what, high, the, relation, as, a, 218, court,...  
932  [214, what, high, the, a, role, court, state, ...  

[933 rows x 3 columns]

In [8]:
mv.to_csv('que.csv', index=False)

In [9]:
mv['tags']=mv['tags'].apply(lambda x:" ".join(x))
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=500,stop_words='english')
vector = cv.fit_transform(mv['tags']).toarray().astype(float)
print(vector)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [10]:
import numpy as np
import pandas as pd
import sklearn
import nltk
from nltk.stem.porter import PorterStemmer
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import CountVectorizer


def check1(s,mv):
    mv['tags'] = mv['tags'].apply(lambda x: " ".join(map(str, x)))

    user_input=s.lower().strip()

    user_vector = cv.transform([user_input]).toarray()

    cosine_similarities = cosine_similarity(user_vector, vector)

    top_indices = cosine_similarities.argsort()[0][-5:][::-1]

    for index in top_indices:
        num=mv['prompt'][index]
        title = mv['output'][index]
        print(num,title)


mv=pd.read_csv('que.csv')
title=str(input())
check1(title,mv)

What is the definition of 'Panchayat' in the
What is the definition of 'Panchayat' in the Constitution of India? In the Constitution of India, a 'Panchayat' is defined as an institution (by whatever name called) of self-government constituted under article 243B, for the rural areas.
What is the definition of a 'Registrar' as per the Constitution of India? A 'Registrar' as defined by the Constitution of India refers to the Central Registrar appointed by the Central Government for multi-State co-operative societies and the Registrar for co-operative societies appointed by the State Government under the law made by the Legislature of a State in relation to co-operative societies.
What is the definition of a 'co-operative society' as per the Constitution of India? A 'co-operative society' as defined by the Constitution of India is a society registered or deemed to be registered under any law relating to co-operative societies for the time being in force in any State.
Can a state legislatur

In [11]:
import numpy as np
import pandas as pd
import sklearn
import nltk
from nltk.stem.porter import PorterStemmer
from sklearn.metrics.pairwise import cosine_similarity


mv=pd.read_csv('xyz.csv')

In [14]:
mv.head()

article                                              title  \
0       0                                           Preamble   
1       1                    Name and territory of the Union   
2       2           Admission or establishment of new States   
3       3  Formation of new States and alteration of area...   
4       4  Laws made under articles 2 and 3 to provide fo...   

                                         description  \
0  WE, THE PEOPLE OF INDIA, having solemnly resol...   
1  (1) India, that is Bharat, shall be a Union of...   
2  Parliament may by law admit into the Union, or...   
3  Parliament may by law—  (a) form a new State b...   
4   (1) Any law referred to in article 2 or artic...   

                                                tags  
0                                  ['preamble', '0']  
1  ['name', 'and', 'the', 'union', 'territory', '...  
2  ['states', 'admission', 'establishment', 'new'...  
3  ['states', 'existing', 'boundaries', 'and', 'f...  
4  ['laws', 'schedules', 'supplemental,', 'first'...

In [13]:
mv['description'] = mv['description'].str.replace('\n', ' ')

In [15]:
mv.to_csv('main.csv', index=False)